### ISSUE TITLE
Error screen 

### ISSUE THREAD

**Issue by nilotpaladdy** [akystyle/sample#1]

**Comment by nilotpaladdy** [comment]
![screenshot_2016-02-28-14-05-57](https://cloud.githubusercontent.com/assets/17526376/13378839/79d0ea94-de39-11e5-9cce-b6a25bf5704d.png)

**Comment by nilotpaladdy** [comment]
[Carpool.txt](https://github.com/akystyle/sample/files/149862/Carpool.txt)

**Comment by akystyle** [comment]
Closing this sample bug
