### ISSUE TITLE
"App shows unknown message after choosing destination (Registered as ""Pooler"")"

### ISSUE THREAD

**Issue by nilotpaladdy** [akystyle/sample#4]
1. Install the app
"2. Register as ""Pooler"" - ID huhuhu pass - huhuhu"
3. App auto detects the location from gps
4. Enter the destination
"5. App shows message ""Select owner - hdhs, hshd etc.."""
6. Dissapears when i click anywhere on the screen (If i select the message portion it glows in yellow color)
7. After i change the location the same message appears
![screenshot_2016-02-28-14-05-57](https://cloud.githubusercontent.com/assets/17526376/13464981/93c3b99a-e0b9-11e5-94bf-2830433f2330.png)

**Comment by akystyle** [comment]
As discussed, this is as designed

Closing the bug
